Update setup.py
Stability-AI/generative-models pull request #3
Opened 2023-06-24 17:16 UTC by KARTHIK07GUPTA

author: Specifies the name of the package author.
author_email: Specifies the email address of the package author. install_requires: Specifies the dependencies required by the package. Add the necessary dependencies as a list of strings. entry_points: Allows you to define command-line scripts or other entry points for your package. It associates the sgm-cli command with the main() function in the sgm.cli module. package_data: Specifies additional files or data to be included with the package. In this example, it includes all text files in the data directory of the sgm package. license: Specifies the license under which the package is distributed (e.g., "MIT", "Apache License 2.0", etc.). classifiers: Provides classifiers or tags for the package that indicate its properties, target audience, and compatibility. Feel free to modify these fields according to your package's specific requirements.

2023-06-24 20:33 UTC, brycedrennan requested changes
Filled in values are wrong.

2023-06-25 07:54 UTC, airdrop11111 commented
I noticed a small bug in your code. Have you considered using XYZ to fix it?

2023-06-26 07:48 UTC, benjaminaubin commented
The `setup.py` package will be updated with final values (authors, emails, license, requirements) for the public release date mid July

2023-06-26 15:16 UTC, ben-alkov commented on setup.py
> +        "Programming Language :: Python :: 3",
Current README advises "This is tested under python3.8 and python3.10. For other python versions, you might encounter version conflicts."

2023-07-18 11:07 UTC, closed without merging