update sv4d sampling script and readme
Stability-AI/generative-models pull request #392
Opened 2024-07-31 19:18 UTC by chunhanyao-stable

2024-08-01 05:49 UTC, voletiv requested changes

2024-08-01 05:49 UTC, voletiv commented on .vscode/launch.json
Remove this file

2024-08-01 05:49 UTC, voletiv commented on README.md
> +    - Please check our [project page](), [tech report]() and [video summary]() for more details.
Is this removal of links on purpose?

2024-08-01 05:49 UTC, voletiv commented on sgm/modules/spacetime_attention.py
> +        return out
Unnecessary, please remove

2024-08-01 19:43 UTC, chunhanyao-stable commented
@voletiv I resolved all the comments. Please check again. Thanks!

2024-08-02 04:10 UTC, voletiv approved these changes

2024-08-02 04:10 UTC, merged